# Site settings
title: Mott status
description: My current motivation status

# User settings
username: Terje
user_title: Software Developer
email: terjerusska@gmail.com
github_username:  TerjeRusska

exclude: ['package.json', 'src' , 'node_modules']
