# Site settings
title: Mott status
description: My current motivation status
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Terje
user_title: Software Developer
email: terjerusska@gmail.com
github_username:  TerjeRusska

exclude: ['package.json', 'src' , 'node_modules']
